name: Deploy
on:
push: branches â€“ master
jobs:
build:
runs-on: ubuntu-latest
steps:
uses: actions/checkout@v2
uses:	akhileshns/heroku-deploy@v3.12.12

heroku_api_key: ${{secrets.HEROKU_API_KEY}}

heroku_app_name:	"artesanias-tee"
heroku_email: "roter.herbst@gmail.com"
